[workspace]
resolver = "2"
members = ["core", "bindings"]

[workspace.package]
version = "0.1.0"
rust-version = "1.76"
edition = "2021"
license = "GPL-3.0-only"
authors = [""]

[workspace.dependencies]
anyhow = { version = "1.0.79" }
ethers-contract = { version = "2.0.13" }
ethers-core = { version = "2.0.13" }
ethers-providers = { version = "2.0.13" }
revm = { version = "5.0.0", features = ["ethersdb", "tokio"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.36.0" }

[profile.release]
lto = true
strip = "symbols"
